Feature/signup signin
greybutton/task_manager pull request #7
Opened 2019-03-27 04:00 UTC by greybutton

2019-03-28 10:39 UTC, artempartos requested changes

2019-03-28 10:39 UTC, artempartos commented on app/views/layouts/application.html.slim
> +  .navbar.navbar-default.navbar-static-top
navbar out of body

2019-03-28 15:13 UTC, greybutton commented on app/views/layouts/application.html.slim
> +  .navbar.navbar-default.navbar-static-top
fixed

2019-04-01 16:59 UTC, Andrew8xx8 approved these changes

2019-04-02 15:28 UTC, merged